name: first

#gh filter pattern cheat sheet - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
#on: push
#on: [push, pull_request]
on:
  push:
    branches:
      - main
      - feature/*
      - release/*
  pull_request:
    branches: [ "main" ]

jobs: 
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: env | sort
      - name: Step Three - Print Date
        run: |
              date
              # hardware clock
              sudo hwclock --show

  job2:
    needs: job1
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"
      - name: Step Three - Print Date
        run: "Get-Date"

  job3:
    #needs: [job1, job2]
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: "date -j -vJulm -v20d -v1999y '+%A'"

  job4:
    needs: [job1, job2, job3]
    name: Forth Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v4
      - name: Step Two
        run: "date"